### ISSUE TITLE
cards overlap on each other

### ISSUE THREAD

**Issue by roc634** [PiotrMachowski/Home-Assistant-Lovelace-HTML-Jinja2-Template-card#14]
Hello,
Thanks for creating such a great project. I want to quote part of a weather forecast page and show it as a card in  Home Assistant. Your project is able to show specific part of a page which meets my needs. However, when I try to add another card, they overlap on each other and I can't find a solution to that. Could you please help me with that? Thanks. 

configuration for card 1:
> type: custom:html-template-card
> picture_elements_mode: true
> ignore_line_breaks: true
> content: >
>   <div style="position: absolute; height: 600px; width: 660px; overflow: hidden;
>   margin-top: 0px; margin-left: 0px;"> <iframe
>   src="http://products.weather.com.cn/product/radar1/index/procode/JC_RADAR_AZ9200_JB.shtml"
>   frameborder="0" allowfullscreen="false" allowtransparency="false"
>   style="width: 100%; min-height: 1000px; border: 0; margin-top: 0px;
>   margin-bottom: 0px; position: absolute; top: -350px; left: -0px;
>   transform:scale(0.7);"></iframe> </div>

configuration for card 2:
> type: custom:html-template-card
> picture_elements_mode: true
> ignore_line_breaks: true
> content: >
>   <div style="position: absolute; height: 220px; width: 730px; overflow: hidden;
>   margin-top: 0px; margin-left: 0px;"> <iframe
>   src="http://www.weather.com.cn/weather/101280608.shtml" frameborder="0"
>   allowfullscreen="false" allowtransparency="false" style="width: 100%;
>   min-height: 1000px; border: 0; margin-top: 0px; margin-bottom: 0px; position:
>   absolute; top: -360px; left: -145px; transform:scale(0.7);"></iframe> </div>
> 

cards shown in editing mode:
<img width="482" alt="2022-2-17 15-16-1" src="https://user-images.githubusercontent.com/49619054/154424744-544640fd-e561-4cef-b056-ff9778d39abb.png">

cards shown in page:
<img width="453" alt="2022-2-17 15-16-19" src="https://user-images.githubusercontent.com/49619054/154424767-2ecdaaed-d631-4da5-b46a-d488c1895fc0.png">

**Comment by PiotrMachowski** [comment]
Why do you use this card instead of built-in [webpage card](https://www.home-assistant.io/lovelace/iframe/)? 

By the way, you probably shouldn't use `picture_elements_mode`

**Comment by PiotrMachowski** [comment]
The problem was with styles you have used, here is a fixed version:
```yaml
type: custom:html-template-card
picture_elements_mode: true
ignore_line_breaks: true
content: >
  <div style="height: 600px; width: 100%; overflow: hidden; --scale: 0.7;">
  <iframe
  src="http://products.weather.com.cn/product/radar1/index/procode/JC_RADAR_AZ9200_JB.shtml"
  frameborder="0" allowfullscreen="false" allowtransparency="false"
  style="width: calc(100%/var(--scale)); height: calc(100%/var(--scale));
  transform:scale(var(--scale)); transform-origin: top left;"></iframe> </div>
```

**Comment by roc634** [comment]
Thank you very much for your prompt rely. I've tried the built-in webpage card, but its function is so simple that I have to give up. Your card can show specific area of a page and that's what I needs. Thanks again. Have a nice day!

**Comment by roc634** [comment]
I‘ve also tried to turn on and off picture_elements_mode. I noticed that picture_elements_mode could make full use of the space of the card, so I prefered to use it. Thanks for your advice.
