### ISSUE TITLE
Card background is forced opaque despite semi-transparent card background in theme

### ISSUE THREAD

**Issue by DarkFox** [PiotrMachowski/Home-Assistant-Lovelace-HTML-Jinja2-Template-card#3]
When using a theme with semi-transparent card backgrounds, the transparency doesn't work on html-template-card.

**Comment by PiotrMachowski** [comment]
I use semi-transparent cards and it works perfectly well, so the problem is probably in the theme itself.
Could you show your theme config?

**Comment by DarkFox** [comment]
I dug around a bit more, and it seems to only happen when using it in combination with vertical-stack-in-card.

Vertical-stack-in-card is supposed to remove the sub-card's background and border, but it doesn't look like it does for this card.

**Comment by PiotrMachowski** [comment]
I will take a look, for now you can probably use `picture_elements_mode`

**Comment by PiotrMachowski** [comment]
Does is work in `picture_elements_mode`?

**Comment by DarkFox** [comment]
Sort of, but that also removes the margin/padding, so I'll just stick with the mod-card workaround for now.

**Comment by PiotrMachowski** [comment]
Rendering issues have been fixed in version 1.0.2
