### ISSUE TITLE
Multiline Jinja statements fail to render

### ISSUE THREAD

**Issue by milks808** [PiotrMachowski/Home-Assistant-Lovelace-HTML-Jinja2-Template-card#31]
Not sure of the precise terminology here but splitting a jinja statement, (e.g. assignment) across multiple lines appears to break the HTML generation, for example:

```
type: custom:html-template-card
content: |
  {% set a = True %}
  {{a}}
```

renders 'True', while the follow fails to render anything

```
type: custom:html-template-card
content: |
  {%
    set a = True
  %}
  {{a}}
```

this is particularly problematic when attempting to do iteration or conditionals

**Comment by PiotrMachowski** [comment]
You have to use `ignore_line_breaks: true` to handle such cases
