### ISSUE TITLE
Card doesn't work for non-admin accounts

### ISSUE THREAD

**Issue by DarkFox** [PiotrMachowski/Home-Assistant-Lovelace-HTML-Jinja2-Template-card#4]
When trying to view a template card when logged in as a user that's part of the 'users' group, the card won't load due to getting a `401: Unauthorized` response from the `/api/template` API endpoint. Changing the user's group to admin makes it work again.

I don't know the specifics of the endpoint, so this might need a change in Home Assistant, but I suppose at least the documentation should mention it.

**Comment by PiotrMachowski** [comment]
I should be working from version 1.0.2
