### ISSUE TITLE
does this still work with ver 0.115 and above

### ISSUE THREAD

**Issue by balajeek** [PiotrMachowski/Home-Assistant-Lovelace-HTML-Jinja2-Template-card#8]
I installed it from HACS and trying to use it but I get error 'no card type configured'

**Comment by PiotrMachowski** [comment]
Can you share your config?

**Comment by balajeek** [comment]
Sorry I posted it too early, I actually copied the piece of the code said it your example and that did not work, but I modified it by removing "views/cards" and it worked.  thanks so much.  now that I have added many links and its very useful.
