### ISSUE TITLE
List of files from a directory

### ISSUE THREAD

**Issue by tunerooster** [PiotrMachowski/Home-Assistant-Lovelace-HTML-Jinja2-Template-card#9]
I would like to get a list of files from a directory.  Ideally, I would like to spawn a shell command (ls -t | head) to do this, like node's "child_process" package.  Is it possible to:

* require('child_process') in the content: for this card?

If not, is there *any* way to do this?

The files would be stored in a list which I would traverse...  Thanks!!

**Comment by PiotrMachowski** [comment]
It's not possible to do it in a card, you would have to create a sensor for it.
This one should do the job: https://www.home-assistant.io/integrations/sensor.command_line/
